version: 2.1
orbs:
  node: circleci/node@4.7.0
  nx: nrwl/nx@1.0.0

#################################################################################
# Aliases
#################################################################################
default_executor: &default_executor
  executor:
    name: node/default
    tag: '14.16'

filter_branch: &filter_branch
  filters:
    branches:
      ignore: gh-pages

#################################################################################
# Commands
#################################################################################
commands:
  yarn-install:
    parameters:
      cache-version:
        type: string
        default: v4
        description: Change the cache version if you need to clear the cache for any reason.

    steps:
      - restore_cache:
          keys:
            - node-deps-<<parameters.cache-version>>-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            - node-deps-<<parameters.cache-version>>-{{ checksum "package.json" }}
            - node-deps-<<parameters.cache-version>>

      - run:
          name: yarn install
          command: |
              CKSUM_BEFORE=$(cksum yarn.lock)
              yarn install
              CKSUM_AFTER=$(cksum yarn.lock)
            
              if [[ $CKSUM_BEFORE != $CKSUM_AFTER ]]; then
                echo "yarn.lock was modified unexpectedly - terminating"
                exit 1
              fi
      
      - save_cache:
          key: node-deps-<<parameters.cache-version>>-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - packages/big-design/node_modules
            - packages/big-design-theme/node_modules
            - packages/big-design-icons/node_modules
            - packages/configs/node_modules
            - packages/docs/node_modules
            - packages/examples/node_modules
  
  pre-setup:
    steps:
      - checkout
      - node/install-yarn:
          version: 1.22.15
      - yarn-install
      - nx/set-shas:
          main-branch-name: master
      - attach-built-icons

  attach-built-icons:
    steps:
      - attach_workspace:
          at: .

#################################################################################
# Jobs
#################################################################################
jobs:
  agent:
    <<: *default_executor
    environment:
    steps:
      - pre-setup
      - run: yarn nx-cloud start-agent

  build-icons:
    <<: *default_executor
    steps:
      - pre-setup
      - run: yarn nx run @bigcommerce/big-design-icons:build
      - persist_to_workspace:
          root: .
          paths:
            - packages/big-design-icons/dist

  build:
    <<: *default_executor
    environment:
      # NX_CLOUD_DISTRIBUTED_EXECUTION: 'true'
    steps:
      - pre-setup
      - run: yarn nx affected --base=$NX_BASE --target=build --exclude=@bigcommerce/docs,@bigcommerce/big-design-icons --parallel

  test:
    <<: *default_executor
    environment:
      # NX_CLOUD_DISTRIBUTED_EXECUTION: 'true'
    steps:
      - pre-setup
      - run: yarn nx affected --base=$NX_BASE --target=test --parallel

  typeCheck:
    <<: *default_executor
    environment:
      # NX_CLOUD_DISTRIBUTED_EXECUTION: 'true'
    steps:
      - pre-setup
      - run: yarn nx affected --base=$NX_BASE --target=typeCheck --parallel

  build-docs:
    <<: *default_executor
    steps:
      - pre-setup
      - restore_cache:
          keys:
            - nextjs-nx-cache-v2-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            - nextjs-nx-cache-v2-{{ checksum "package.json" }}
            - nextjs-nx-cache-v2
      - run: yarn nx run @bigcommerce/docs:build
      - save_cache:
          key: nextjs-nx-cache-v2-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - packages/docs/.next

  stop-agents:
    <<: *default_executor
    steps:
      - pre-setup
      - run: yarn nx-cloud stop-all-agents

#################################################################################
# Workflows
#################################################################################
workflows:
  version: 2
  build_and_test:
    jobs:
      # - agent:
      #     <<: *filter_branch
      #     name: 'agent1'

      # - agent:
      #     <<: *filter_branch
      #     name: 'agent2'

      # - agent:
      #     <<: *filter_branch
      #     name: 'agent3'
      - build-icons:
          <<: *filter_branch

      - build:
          <<: *filter_branch
          requires:
            - build-icons

      - test:
          <<: *filter_branch
          requires:
            - build-icons

      - typeCheck:
          <<: *filter_branch
          requires:
            - build-icons

      - build-docs:
          <<: *filter_branch
          requires:
            - build-icons

      # - stop-agents:
      #     <<: *filter_branch
      #     requires:
      #       - build
      #       - test
